# Generated by Django 4.2.7 on 2026-03-20 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=150)),
                ('requester_phone', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car / Sedan'), ('suv', 'SUV / MUV'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck / Commercial'), ('other', 'Other')], default='car', max_length=20)),
                ('issue_type', models.CharField(choices=[('flat_tyre', 'Flat Tyre'), ('engine_failure', 'Engine Failure'), ('battery_dead', 'Battery Dead'), ('accident', 'Accident'), ('out_of_fuel', 'Out of Fuel'), ('overheating', 'Overheating'), ('electrical', 'Electrical Issue'), ('other', 'Other')], default='other', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('location_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Provider Assigned'), ('en_route', 'Technician En Route'), ('in_progress', 'Service In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('assigned_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_assignments', to='services.serviceprovider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Request',
                'verbose_name_plural': 'Emergency Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=150)),
                ('technician_phone', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='emergency.emergencyrequest')),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatches',
            },
        ),
    ]
