# Generated by Django 4.2.7 on 2026-05-17 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('emergency', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type_text', models.CharField(help_text='Freeform service type requested by customer', max_length=200)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car / Sedan'), ('suv', 'SUV / MUV'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck / Commercial'), ('other', 'Other')], default='car', max_length=20)),
                ('vehicle_make', models.CharField(blank=True, help_text='e.g. Maruti, Honda', max_length=100)),
                ('vehicle_model', models.CharField(blank=True, help_text='e.g. Swift, City', max_length=100)),
                ('vehicle_year', models.CharField(blank=True, max_length=4)),
                ('vehicle_reg_no', models.CharField(blank=True, help_text='Registration / Number plate', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('location_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending — Awaiting Provider'), ('accepted', 'Accepted by Provider'), ('declined', 'Declined by Provider'), ('in_progress', 'Service In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled by Customer')], default='pending', max_length=20)),
                ('provider_note', models.TextField(blank=True, help_text='Note from provider when accepting or declining')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_service_requests', to='services.serviceprovider')),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
