# Generated by Django 4.2.7 on 2026-05-17 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='emergency.servicerequest'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='emergency.emergencyrequest'),
        ),
    ]
